export const authType = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: " LOGOUT_SUCCESS",
    LOGOUT_FAILURE: " LOGOUT_FAILURE"
}




export const categoryType = {
    GET_ALL_CATEGORY_REQUEST : 'GET_ALL_CATEGORY_REQUEST',
    GET_ALL_CATEGORY_SUCCESS :'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_FAILURE: 'GET_ALL_CATEGORY_FAILURE',
    ADD_NEW_CATEGORY_REQUEST: 'ADD_NEW_CATEGORY_REQUEST',
    ADD_NEW_CATEGORY_SUCCESS: 'ADD_NEW_CATEGORY_SUCCESS'
}




export const productType = {
    GET_ALL_PRODUCT_SUCCESS: 'GET_ALL_PRODUCT_SUCCESS',
    ADD_NEW_PRODUCT_REQUEST: ' ADD_NEW_PRODUCT_REQUEST',
    ADD_NEW_PRODUCT_SUCCESS: ' ADD_NEW_PRODUCT_SUCCESS',
    ADD_NEW_PRODUCT_FAILURE: 'ADD_NEW_PRODUCT_FAILURE'
}